<?php $this->placeholder('h2')->set('Modifier un Article') ?>

<?= $this->formArticle->renderForm(false) ?>
<?= $this->formArticle->getElement('id') ?>
<?= $this->formArticle->getElement('designation') ?>
<?= $this->formArticle->getElement('image') ?>

<?php
$this->formArticle->getElement('categorie_id')->setMultiOptions($this->categories);
?>
<?= $this->formArticle->getElement('categorie_id') ?>

<button type="submit" class="btn btn-xs btn-primary">Modifier</button>
</form>