<?php $this->placeholder('h2')->set('Supprimer un Article') ?>

<form method="post">
    <p>Etes-vous sûr de vouloir supprimer l'Article "<?=$this->escape($this->article->getDesignation())?>" ?</p>
    <p>
        <button type="submit" name="confirm" value="Oui" class="btn btn-primary">Oui</button>
        <button type="submit" name="confirm" value="Non" class="btn btn-default">Non</button>
    </p>
</form>