<fieldset>
    <!-- Form Name -->
    <legend>Détail de l'Article</legend>

    <!-- Text input-->
    <div class="form-group">
        <label class="col-md-4 control-label" for="designation">Désignation</label>  
        <div class="col-md-6">
            <input id="designation" name="designation" placeholder="" class="form-control input-md" type="text" value="<?= $this->article->getDesignation() ?>" disabled>
        </div>
    </div>
</fieldset>

<ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#fournisseurs">Fournisseurs</a></li>
</ul>

<div class="tab-content">
    <a class="btn btn-xs btn-primary" href="<?= $this->RUrl(['controller' => 'articleFournisseur', 'action' => 'add', 'idarticle' => $this->article->getId()])?>">Ajouter</a>
    
    <?php
    if ($this->articleFournisseur) {
    ?>
        <div id="aticles" class="tab-pane fade in active">
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Fournisseur</th>
                        <th>Prix</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($this->articleFournisseur as $af) : ?>
                    <tr>
                        <td>
                            <?= $this->escape($af->getFournisseur()->getNom()) ?>
                        </td>
                        <td>
                            <?= $this->escape($af->getPrix()) ?>
                        </td>
                        <td>
                            <a class="btn btn-xs btn-primary" href="<?= $this->Url(['controller' => 'articleFournisseur', 'action' => 'show', 'idArticle' => $af->getId()]) ?>">Afficher</a>
                            <a class="btn btn-xs btn-warning" href="<?= $this->RUrl(['controller' => 'articleFournisseur', 'action' => 'modify', 'id' => $af->getId()]) ?>">Modifier</a>
                            <a class="btn btn-xs btn-danger" href="<?= $this->RUrl(['controller' => 'articleFournisseur', 'action' => 'remove', 'id' => $af->getId()]) ?>">Supprimer</a>
                            <a class="btn btn-xs btn-info" href="<?= $this->RUrl(['controller' => 'articleFournisseur', 'action' => 'detail', 'id' => $af->getId()]) ?>">Détail</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    <?php
    }
    ?>
</div>