<!DOCTYPE html> 
<html lang="fr"> 
    <head> 
        <meta charset="utf-8"> 
        <meta name="viewport" content="width=device-width, initial-scale=1.0"> 

        <?= $this->headTitle('Mon Stock')->setSeparator(' - ') ?>

        <link href="<?= $this->baseUrl('css/bootstrap.css') ?>" rel="stylesheet"> 
        
        <?= $this->HeadLink() ?>

        <?= $this->HeadMeta() ?>

        <?= $this->HeadScript() ?>

        <?= $this->HeadStyle() ?>

    </head> 

    <body>
        
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#">Mon Stock</a>
                </div>
                <ul class="nav navbar-nav">
                    <li <?= $this->classActive(['controller' => 'categorie', 'action' => 'index']); ?>><a href="<?=$this->rUrl(['controller' => 'categorie', 'action' => 'index']) ?>">Catégorie</a></li>
                    <li <?= $this->classActive(['controller' => 'article', 'action' => 'index']); ?>><a href="<?=$this->rUrl(['controller' => 'article', 'action' => 'index']) ?>">Article</a></li>
                    <li <?= $this->classActive(['controller' => 'fournisseur', 'action' => 'index']); ?>><a href="<?=$this->rUrl(['controller' => 'fournisseur', 'action' => 'index']) ?>">Fournisseur</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                    <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                </ul>
            </div>
        </nav>
        
        <div class="container">
            <h2><?= $this->placeholder('h2') ?></h2>
            <div class="starter-template">
                <?php echo $this->layout()->content; ?>
            </div>
        </div>

        <script src="<?= $this->baseUrl('js/jquery-3.1.1.js') ?>"></script>
        <script src="<?= $this->baseUrl('js/bootstrap.min.js') ?>"></script> 
        
        <?= $this->InlineScript() ?>
        
    </body> 
</html>


